import React from "react";
import { Card, CardTitle, CardText } from "../../components/core/Card.jsx";
import { Eyebrow } from "../../components/brand/Eyebrow.jsx";
import { Section, SectionHead } from "./Section.jsx";
import { PageHero, Prose, Strong, H2, CheckList, Callout, CTA } from "./Prose.jsx";
export function About({ onNav }) { return <>
  <PageHero eyebrow="About" title="Intentionally small. Proudly unconventional. Allergic to corporate theater." lede="See our mascot." mascot="standing"/>
  <Section narrow><H2 eyebrow="Our story">We wanted to build cool stuff and make a living.</H2><Prose><p>We didn’t start with a grand vision or a plan to change the world. Really, we still don’t.</p><p>Most of our early existence was spent working on projects for other companies. We learned a lot about what works and what doesn’t. We have war stories.</p><p>Since then we’ve worked with startups and 100-billion-dollar giants. Sometimes we do small projects for friends because they have fun ideas.</p><p>We are optimizing for working with <em style={{color:"var(--fg)"}}>genuine, strategically minded people</em> and building cool things that solve real problems.</p><Strong>Ideally, we all make a good living.</Strong></Prose></Section>
  <Section tone="subtle"><SectionHead eyebrow="How we work" title="Four trade-offs we’ve already made."/>
    <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:16}}>
    {[["Speed","Perfection","We’d rather ship something good in two weeks than something perfect in six months."],["Outcomes","Hours","We price on value delivered, not time spent."],["Honesty","Sales","If we can’t help you, we’ll tell you. We’d rather say no than waste your money."],["Simplicity","Complexity","We build the simplest thing that could possibly work. Complexity is a liability."]].map(([a,b,d])=><Card key={a}><div style={{display:"grid",gap:2}}><span style={{fontWeight:700,fontSize:22,color:"var(--fg-brand)"}}>{a}</span><span style={{font:"var(--type-eyebrow)",letterSpacing:"var(--tracking-caps)",textTransform:"uppercase",color:"var(--fg-faint)"}}>over {b}</span></div><CardText>{d}</CardText></Card>)}</div></Section>
  <CTA title="Want to work with us?" sub="17 minutes to see if the math works for your challenges." onNav={onNav}/>
</>; }
export function Careers({ onNav }) { return <>
  <PageHero eyebrow="Careers" title="A small team that punches way above its weight." lede="If you want to solve real problems with smart people and zero corporate theater, you might be a good fit." mascot="labcoat"/>
  <Section><SectionHead eyebrow="What it’s like here" title="Everyone here is senior. Everyone ships."/>
    <div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:16}}>{[["Ship fast, learn faster","We prototype in days and launch in weeks. Your work reaches production quickly, not a backlog."],["AI-native workflow","AI tools daily — not as a gimmick, as a genuine force multiplier."],["Small team, big impact","No layers of management. Everyone’s opinion matters."],["Outcomes over hours","Flexible schedule, async-first. We care about what you deliver."]].map(([t,d])=><Card key={t} variant="soft"><CardTitle>{t}</CardTitle><CardText>{d}</CardText></Card>)}</div></Section>
  <Section tone="subtle" narrow><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:40}}>
    <div><H2>Who we’re looking for</H2><p style={{color:"var(--fg-muted)",marginTop:-16,marginBottom:12}}>We don’t hire often — we’re intentionally small. When we do, we look for people who:</p><CheckList items={["Have deep experience in software engineering, AI/ML or automation","Can talk to clients as comfortably as they write code","Prefer shipping over debating, simplicity over cleverness","Are honest — even when it’s uncomfortable","Want to build cool things and make a good living doing it"]}/></div>
    <Callout tone="label" eyebrow="Open positions"><p style={{fontWeight:700,fontSize:22}}>None right now.</p><p style={{color:"var(--fg-muted)",lineHeight:1.6}}>But we’re always interested in hearing from exceptional people. If you think you’d be a great fit, reach out anyway.</p></Callout></div></Section>
  <CTA title="Interested?" sub="Drop us a line. Tell us what you’re good at and what you’d want to work on." button="Get in touch" onNav={onNav}/>
</>; }
export function Opinions({ onNav }) {
  const ops=[["Most AI projects shouldn’t be built","At least not yet.","We make money building AI solutions, but most AI projects are solutions looking for problems. Sometimes a spreadsheet, a checklist, or hiring another person is the right answer."],["Outcome is the only thing that matters","Everything else is a detail.","Us nerds can get caught up in how things are built. A beautiful piece of code is worthless if it sucks to use."],["Enterprise software is usually terrible","Complexity is not a feature.","Most enterprise software is designed to be sold, not used. Simple tools that do one thing well beat platforms that do everything poorly."],["Meetings are where work goes to die","If it could be an email, it should be an email.","Most meetings exist because someone didn’t want to make a decision or write something down. We bias heavily toward async and written docs."],["Perfect is the enemy of done","Ship it. Learn. Iterate.","We’d rather ship something rough in two weeks and learn from real usage than launch something “ready” that nobody used."]];
  return <>
  <PageHero eyebrow="Controversial opinions" title="Things we believe that might ruffle some feathers." lede="We’re not contrarian for its own sake — these are hard-won lessons from years of watching projects succeed and fail." center/>
  <Section narrow><ol style={{listStyle:"none",padding:0,display:"grid",gap:0}}>{ops.map(([t,s,d],i)=><li key={t} style={{display:"grid",gridTemplateColumns:"72px 1fr",gap:24,padding:"32px 0",borderBottom:"1px solid var(--border)"}}><span style={{font:"700 48px/1 var(--font-condensed)",color:"var(--pl-lime-500)"}}>0{i+1}</span><div style={{display:"grid",gap:8}}><h2 style={{font:"var(--type-h2)",fontSize:28}}>{t}</h2><Eyebrow>{s}</Eyebrow><p style={{color:"var(--fg-muted)",fontSize:17,lineHeight:1.6,marginTop:4}}>{d}</p></div></li>)}</ol></Section>
  <CTA title="Disagree? Let’s argue for 17 minutes." sub="We’ll listen for 15 of them." onNav={onNav}/>
</>; }
