import React from "react";
import { Card, CardTitle, CardText } from "../../components/core/Card.jsx";
import { Eyebrow } from "../../components/brand/Eyebrow.jsx";
import { Section, SectionHead } from "./Section.jsx";
import { PageHero, Prose, H2, CheckList, CTA } from "./Prose.jsx";
export function Who({ onNav }) { return <>
  <PageHero eyebrow="Who we work with" title="We’re selective about who we work with. Here’s why that’s good for you." lede="We don’t take on every project that comes through the door. We build long-term partnerships with companies whose values align with ours — because the best software comes from collaboration between people who give a damn." mascot="farm"/>
  <Section tone="loud" narrow><blockquote style={{font:"var(--type-h2)",fontSize:30,lineHeight:1.25,letterSpacing:"var(--tracking-snug)",color:"var(--fg-brand-deep)",textWrap:"balance",margin:0}}>“We believe the primary purpose of great software is to make the people doing the work happier, more effective, and more able to focus on what they do best.”</blockquote></Section>
  <Section narrow><H2 eyebrow="The underserved middle">Built for companies between $10M and $100M.</H2><Prose><p>You’re large enough to have genuinely complex operational challenges, but not so large that you have a 50-person IT department to throw at them. You’ve outgrown spreadsheets and workarounds, but enterprise vendors treat you like an afterthought.</p><p>That’s exactly where we work. Problems that used to be too expensive to solve are now very much within reach.</p></Prose></Section>
  <Section tone="subtle"><SectionHead eyebrow="What we value in a partner" title="Six things we look for."/>
    <div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:16}}>
    {[["Genuine & direct","If something isn’t working, say so. If you’re not interested, tell us. We’ll do the same."],["Strategically minded","You think about how your business runs, not just whether it runs."],["Curious & open","Interested in new ideas, willing to experiment — practical and grounded, but open to a better way."],["People-first","You want to give your team better tools, not just cut costs."],["Ready to invest","Meaningful improvement takes your time, attention and budget alongside ours."],["Built to last","You’re an established business looking to modernize — not a startup chasing product-market fit."]].map(([t,d])=><Card key={t}><CardTitle>{t}</CardTitle><CardText>{d}</CardText></Card>)}</div></Section>
  <Section narrow><SectionHead eyebrow="Are we a good fit?" title="A quick self-assessment to save us both time."/>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:40}}>
      <div><h3 style={{font:"var(--type-eyebrow)",letterSpacing:"var(--tracking-caps)",textTransform:"uppercase",color:"var(--fg-brand)",paddingBottom:12,borderBottom:"2px solid var(--primary)"}}>Probably a great fit if…</h3><CheckList items={["Your team still runs important processes on spreadsheets, paper forms or email chains","You’ve been meaning to “do something about technology” but haven’t found the right partner","You’ve tried a software project that didn’t go well, and want to try again — smarter","You can point to specific processes that feel unnecessarily manual","Your company is growing and the tools that got you here won’t get you there","You want your team on work that uses their expertise, not data entry"]}/></div>
      <div><h3 style={{font:"var(--type-eyebrow)",letterSpacing:"var(--tracking-caps)",textTransform:"uppercase",color:"var(--danger)",paddingBottom:12,borderBottom:"2px solid var(--danger)"}}>Probably not the right fit if…</h3><CheckList tone="danger" items={["You already have a strong internal development team","You’re looking for the cheapest option rather than the right solution","You need a vendor to execute a predefined spec with no input on approach","Technology decisions require approval from a parent company or external board","You can’t commit time, feedback and budget to a collaborative process"]}/></div>
    </div></Section>
  <Section tone="inverse"><div style={{textAlign:"center",display:"grid",gap:12,marginBottom:28}}><Eyebrow tone="inverse" style={{color:"var(--pl-lime-500)"}}>Industries we serve</Eyebrow><h2 style={{font:"var(--type-h2)",color:"#fff"}}>Software-shaped problems exist everywhere.</h2><p style={{color:"var(--pl-grey-300)"}}>We’ve found them most often in these sectors.</p></div>
    <div style={{display:"flex",flexWrap:"wrap",justifyContent:"center",gap:10}}>{["Manufacturing","Construction","Engineering","Transportation & Logistics","Wholesale & Distribution","Professional Services","Industrial Trades","Mechanical Contracting"].map(i=><span key={i} style={{border:"1.5px solid #5A6249",color:"#F1F2E9",borderRadius:999,padding:"10px 18px",fontSize:15,fontWeight:600}}>{i}</span>)}</div>
    <p style={{textAlign:"center",marginTop:24,fontSize:14,color:"var(--pl-grey-500)"}}>Don’t see your industry? If you’re a mid-market company with operational complexity, we should talk.</p></Section>
  <CTA tone="paper" title="Sound like you?" sub="No pitch deck, no hard sell — just an honest discussion about your business and whether we can help." button="Start a conversation" note="Typically responds within one business day" onNav={onNav}/>
</>; }
