import React from "react";
import { Kicker, DisclaimerBand } from "./Kicker.jsx";
const root=()=>{const l=document.querySelector('link[href$="styles.css"]');return l?l.href.replace(/styles\.css$/,""):"/"};
const ARROW=<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M5 12h14M12 5l7 7-7 7"/></svg>;
/** One inline ad-break unit per Gazette page. kind: pharma | farms | political | lawyer */
export function AdBreak({kind="pharma",style}) {
  const wrap={border:"1.5px solid var(--border-strong)",display:"grid",...style};
  if(kind==="pharma") return <aside style={wrap}><div style={{padding:"18px 20px",display:"grid",gridTemplateColumns:"1fr auto",gap:16,alignItems:"center",background:"var(--bg-elevated)"}}><div style={{display:"grid",gap:6}}><Kicker section="Advertisement" tone="ad"/><p style={{font:"800 26px/1.05 var(--font-news)",fontStretch:"80%",textTransform:"uppercase",color:"var(--fg-brand)"}}>Now treating: chronic spreadsheets.</p><p style={{font:"var(--type-news-body)",color:"var(--fg-muted)"}}>PickleLlama Automation. Side effects may include weekends.</p></div><img src={root()+"assets/mascot/pose-labcoat.png"} alt="" style={{height:120}}/></div><DisclaimerBand left="Side effects may include leaving at 5, sudden free time, finishing by lunch" tone="green"/></aside>;
  if(kind==="farms") return <aside style={wrap}><div style={{padding:"18px 20px",display:"grid",gridTemplateColumns:"auto 1fr",gap:16,alignItems:"center",background:"var(--bg-brand-soft)"}}><img src={root()+"assets/mascot/scene-farm.png"} alt="" style={{height:110}}/><div style={{display:"grid",gap:6}}><Kicker section="Public service" tone="ad"/><p style={{font:"800 26px/1.05 var(--font-news)",fontStretch:"80%",textTransform:"uppercase",color:"var(--fg-brand-deep)"}}>Every year, millions of spreadsheets are subjected to VLOOKUP.</p><p style={{font:"var(--type-news-body)",color:"var(--fg-muted)"}}>Choose free-range, grass-fed software. PickleLlama Farms.</p></div></div><DisclaimerBand left="Cruelty-free · Ethically sourced · Spreadsheet-free" tone="paper"/></aside>;
  if(kind==="political") return <aside style={{...wrap,border:"none",background:"var(--news-ink)",color:"var(--bg)"}}><div style={{padding:"22px 24px",display:"grid",gridTemplateColumns:"1fr auto",gap:16,alignItems:"center"}}><div style={{display:"grid",gap:8}}><span style={{font:"var(--type-kicker)",textTransform:"uppercase",letterSpacing:".12em",color:"var(--news-red)"}}>Paid political advertisement</span><p style={{font:"900 34px/.95 var(--font-news)",fontStretch:"75%",textTransform:"uppercase"}}>He shipped it the same day.<br/><span style={{color:"var(--news-red)"}}>What is he hiding?</span></p><p style={{font:"var(--type-news-small)",color:"var(--pl-grey-500)"}}>No discovery phase. No steering committee. No Phase Two. Is this who you want in your dispatch office?</p></div><img src={root()+"assets/mascot/pose-standing.png"} alt="" style={{height:130,filter:"grayscale(1) contrast(1.4) brightness(.8)"}}/></div><DisclaimerBand left="Paid for by the Spreadsheet Lobby" tone="red"/></aside>;
  return <aside style={{...wrap,borderColor:"var(--news-red)",borderWidth:3}}><div style={{padding:"18px 20px",display:"grid",gap:8,background:"var(--bg-elevated)",textAlign:"center"}}><p style={{font:"900 32px/.95 var(--font-news)",fontStretch:"75%",textTransform:"uppercase",color:"var(--news-red)"}}>Injured by a spreadsheet?</p><p style={{font:"800 20px/1.1 var(--font-news)",fontStretch:"80%",textTransform:"uppercase"}}>You may be entitled to free time.</p><p style={{font:"var(--type-news-small)",color:"var(--fg-muted)"}}>VLOOKUP strain · Tab fatigue · Circular-reference exposure · Repetitive save-changes injury</p><p style={{font:"900 28px/1 var(--font-news)",fontStretch:"75%",letterSpacing:".04em",marginTop:6}}>1-800-ASK-YOUR-BOSS</p></div><DisclaimerBand left="Not a law firm. Not a phone number." tone="ink"/></aside>;
}
